# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: /images/logo.png
# logo_src: "https://cdn-icons-png.flaticon.com/512/3142/3142083.png"

# Theme Main Subtitle
subtitle_main: Let's Talk TV

# Theme Secondary subtitle
susbtitle_secondary: The goal of this blog is to give recommendations through my "Why You Should Watch" posts, explore the fascinating techniques or messages behind great shows through my "Deep Dive" posts, and talk about my relationship with television, in general.

# Footer About Section
about_footer: Logo made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
# comments:
#   # Disqus comments
#   disqus_shortname: klugjo
#   # Facebook comments
#   facebook:
#     appid:
#     comment_count: 5
#     comment_colorscheme: light

# Google Analytics Tracking ID
# google_analytics:

# Social Accounts
# twitter_url: https://twitter.com/?lang=en
# facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
# dribble_url: https://dribbble.com/
github_url: https://github.com/klugjo/hexo-theme-phantom/commits?author=klugjo
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
email_url: \#
# rss_url: \#
