# Header
menu:
  Home: /
  Why You Should Watch: /tags/Why-You-Should-Watch/
  Deep Dives: /tags/Deep-Dives/
  Episode Analysis: /tags/Episode-Analysis
  Archives: /archives
  # About: /about.html

# Logo Image Source
logo_src: /little_screen_cinema/images/logo.png
# logo_src: "https://cdn-icons-png.flaticon.com/512/3142/3142083.png"

# Theme Main Subtitle
subtitle_main: Let's Talk TV.

# Theme Secondary subtitle
susbtitle_secondary: The goal of this blog is to give recommendations, explore the fascinating techniques or messages behind great shows, and talk about my relationship with television, in general. Each post gives proper information regarding spoilers, so you can click on any post with no fear!

# Footer About Section
about_footer: Logo made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
# comments:
#   # Disqus comments
#   disqus_shortname: klugjo
#   # Facebook comments
#   facebook:
#     appid:
#     comment_count: 5
#     comment_colorscheme: light

# Google Analytics Tracking ID
# google_analytics:

# Social Accounts
# twitter_url: https://twitter.com/?lang=en
linkedin_url: https://www.linkedin.com/in/marco-polimeni/
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
# dribble_url: https://dribbble.com/
github_url: https://github.com/mpolimen
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
email_url: mailto:stats3434@gmail.com
# rss_url: \#
